os: windows
language: shell
before_install:
  - choco install python --version=3.7
  - python -m pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
  - pip install pyinstaller
script:
  - bash -c echo "Tests would go here"
before_deploy:
  - pyinstaller -F suda.py
deploy:
  - provider: releases
    user: $GITHUB_USER
    password: $GITHUB_PASS
    file_glob: true
    file: dist/suda.exe
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
      tags: true
  - provider: pypi
    user: $TEST_PYPI_USER
    password: $TEST_PYPI_PASS
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      all_branches: true
      tags: true